version: '3'

services:
    app:
      build:
        context: ./
        dockerfile: app.docker
      stdin_open: true
      tty: true
      volumes: &appVolumes
        - '../.:/var/www'
        - './composer-auth.json:/root/.composer/auth.json' # PHP Composer Credentials

